### ISSUE TITLE
Add Market Stats Widget

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#132]
From #125 we need to create a javascript market cap widget. This will also be used for Primecoin's website so it should be extensible. 

It should show:
- Current price per coin
- Total coins
- Market Cap

@jvanoel will handle the design, but we still need a javascript guru to handle the data. Will look around. @jvanoel can you add a mockup screenshot here?

**Option #1:** 
Rip data from [Coinmarketcap](http://coinmarketcap.com/). 

**Option #2:**
Rip data from the [Vircurex API](https://vircurex.com/welcome/api?locale=en).

**Comment by Gnewt** [comment]
I can do the JavaScript easy peasy! Any preference between CoinMarketCap and Vircurex? CMC provides both of the pieces of info we want, but I don't know how friendly they are with scraping their page (+ it would cause all Peercoin.net visitors to consistently request the whole CMC site in the background). I think Vircurex probably makes more sense, though the results I'm getting from their API are mildly funky.

**Comment by Gnewt** [comment]
Vircurex's weirdness is probably caused by there being no direct USD/PPC volume. I think we'll get better results with two API calls -- one to get PPC/BTC price, one to get BTC/USD price. Does that sound reasonable?

**Comment by super3** [comment]
Yeah I actually was working on a project to turn CMC into a json stream, but just got busy. Yeah that's what I was thinking and/or could use Bitcoin Average for BTC/USD price. Either one works.

**Comment by Gnewt** [comment]
To avoid cross-domain issues, I think it makes sense to cache that data on the peercoin.net server and then update live from that file. Here's a workflow I see:

Client:
1. User visits Peercoin.net
2. Script on peercoin.net asks for peercoin.net/tickerinfo.php or something similar

Server:
1. tickerinfo.php loads cached price/volume from database (assuming we can use MySQL?)
2. If it's more than x seconds old, grab a new set of data from Vircurex or CMC, otherwise return cached data (as JSON)

Client:
1. Client uses JSON data returned to populate objects on screen
2. timeout is set to update the widget in x seconds

I could do this very easily, but I'd like your opinion on which methodology is best. Unless we wanna do funky stuff with iFrames, we can't really have the client requesting data directly from CoinMarketCap or Vircurex (well... we can with a policy but it is probably easier to do it serverside)

**Comment by super3** [comment]
Sounds like a plan. I'd rather use Sqlite3 than maintain a database. I might have some code for this already, but you have to make it work.

https://github.com/super3/millib
