### ISSUE TITLE
Text Edits

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#33]
I noticed some errors or things that sounded kind of funky. Maybe we can clean them up a bit. Here are some suggestions...
- Under the features section, this sentence: "Cryptcurrency must be sustainable to last the test of time as a form of money."

"Cryptocurrency" is missing its "o" and "last" should be changed to "stand." Here is the corrected version...

"Cryptocurrency must be sustainable to stand the test of time as a form of money."
- This sentence: "Peercoin is advanced, sustainable, cryptocurrency." sounds incomplete. Maybe you could add "an" to it like this...

"Peercoin is an advanced, sustainable, cryptocurrency."
- The two sentences above when placed back to back sound kind of repetitive. Maybe there's a way they can be merged together?
- In this sentence "With a market capitalization of over $35 Million USD, Peercoin is disrupting the exciting cryptocurrency landscape." I think we should drop the word exciting. Two words back to back ending with ing sound kind of funky to me, at least in this case. Just my opinion.
- Under the energy efficiency section, the word "generating" is missing its i.

**Comment by iheartcryptocoin** [comment]
Thanks for reviewing.  
- Google "last the test of time" and the first result will be "stand the test of time."  Pretty interchangeable and probably regional preference thing.  

Speaking of regional issues - are you a native American/Canadian, UK,  Antipodean, SA, or etc etc English speaker?  There will be regional issues so should get that context out early anyway.  I speak American, UK, and Australian English and can attest that there are some...weird differences hahaha.

"Cryptocurrency"  - good catch need to add cryptocurrency to a spell checker to machine that fix.  

"is an currency" -
To figure out whether "an" is appropriate test an alternative form - 
"The dollar is...currency"
"The dollar is...an currency"
The first is correct

"Exciting" - attempting a lighter tone at the end by using an energetic adjective as this is a fairly complex and heavy-ish topic.  "Exciting" is one possibility.  This is really a neither here nor there issue though and we would easily go either way having it or not having one.  Will delete   

Two sentences maybe repetitive -
This is an argument structure desgined to build out an idea - EG  
In order to be awesome, Abstract idea A must be true in certain ways.  Specific situation B has what A requires to be awesome.  Therefore specific thing B is awesome in a big abstract way like A.  

These ideas can be combined into one sentence.  That one sentence gets really long and unwieldy when the two ideas are put together. Thus they are currently written as two sentences. If the core idea isn't being communicated by those two sentences they are not serving their purpose, and we should def make a change.  What are some suggestions of other ways to communicate these different ideas? 

generating - excellent catch there, must've been an accidental deletion when pasting in code after the last check.  

Which leads to a question - I've been copy passing code from Dreamweaver into the git text editor to make updates after vetting on my local machine.  Is there a way to link up a code editor (doesn't have to be dreamweaver)  to the git in windows so I can avoid doing this copy/paste dance (and the potential for errors it creates)? 

Thanks again, thorough reading and especially helpful!

**Comment by iheartcryptocoin** [comment]
e939e982216a6a294aa816735a1ff3bcf6d3e7a6

**Comment by Sentinelrv** [comment]
I'm from America, New Jersey specifically. I've actually never heard anyone use the word last in a phrase like that. It has always been stand. I'm ignorant though of how other countries use the phrase. About the an, I'm not a grammatical expert, so I could be wrong here. It just sounded strange and incomplete when I said the sentence aloud. About the coding, I'm not a coder so I can't help you there.

**Comment by Sentinelrv** [comment]
I think I'm going to post a thread asking people to analyze all the changes so far to make sure there isn't anything we're missing like misspellings, grammatical errors. They can also give feedback on what's actually written. Could you watch and respond to this thread just in case there are any great ideas? I'll include a link when I get it up.

**Comment by Sentinelrv** [comment]
Here is the feedback thread I made. Please watch it in case anyone posts anything...

http://www.peercointalk.org/index.php?topic=1060.0

**Comment by iheartcryptocoin** [comment]
Thanks, that's perfect.  I don't know why other folks haven't been chiming in on this so that just the encouragement that they need!

**Comment by iheartcryptocoin** [comment]
And you've got a great eye for editing, so keep it up. It's always better and easier to edit after someone else writes because the first author is invariably too close to the text haha.  If you write anything let me know and I'll def do the same for you. :-)

**Comment by Sentinelrv** [comment]
How about this sentence instead suggested by Roostical in the thread I linked...

"Peercoin is an advanced and sustainable cryptocurrency"

I just can't get over the sentence that's there right now. It doesn't sound right the way it currently is.
