### ISSUE TITLE
Branding conversation

### ISSUE THREAD

**Issue by iheartcryptocoin** [super3/peercoin_website_old#45]
In the chat we talked about incorporating more green into the site to play off of our sustainability and security identity.

There has been lots of chat about PoS - had an idea how to market the idea in addition to being green and secure..  Another tag line could include the idea of  that Peercoin rewards you for using it.  EG  

Peercoin - Stake claim to your reward.

Or something similar.   

Can do some A/B testing with the site with the different branding focuses (one focusing on being green, one on being rewarding) and measure click through to download the client, whitepaper, etc to see which engages users more. This is of course a project for later on.

**Comment by super3** [comment]
I don't think color changes at this point are warranted. The website is very sparse right now, its just essentially a collection of links. We have a bounce rate of about 80% right now. 

We need to focus on adding a few more page of content before we do that. But I agree on the click through.

**Comment by Sentinelrv** [comment]
I'm afraid that tag line won't mean anything to people who don't know yet what proof-of-stake is. I like the tag line we have now: "The sustainable and secure cryptocurrency". It pretty much says everything we need it to right? Peercoin is sustainable because it doesn't require vast amounts of energy to function, which also makes it more secure.

I also think we should limit how much green we use. I looked at the mockups you did for the business cards. I liked the ones with the black and white background, but not the green one. The black and white background helps make the green leaf in the logo stand out more. Those colors also look more professional than green in my opinion.

**Comment by super3** [comment]
Perhaps we should have an infographic made that explains it. Better than a wall of text trying to explain it. Another 99designs contest?

**Comment by super3** [comment]
Closed for later discussion.
